version: '3.7'
services:
  builder:
    build:
      context: .
      dockerfile: "server/Dockerfile"
    ports:
      - "5004:5004"
  ui:
    build:
      context: .
      dockerfile: "static/Dockerfile"
    ports:
      - "8080:8080"
